### ISSUE TITLE
Upload and merge should make it clear that ontologies should already exist in a project

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/webprotege#290] opened 2015-09-03 20:52 UTC
The upload and merge functionality is for existing ontologies (that have have been downloaded) from a project.  It allows people to work ontologies offline.  Not for general uploads.  However, this isn't clear.  See this issue #289.

**Comment by ariutta** [comment] 2015-09-04 17:46
Does this also apply to the "Upload Project..." button (right next to the "Create Project..." button)? I tried to upload the same RDF file using that option, but the "Upload ontology" modal remained open after I clicked OK. Here was the response (with the id number removed):

```json
{
"RESPONSE_TYPE_ATTRIBUTE" : "RESPONSE_TYPE_VALUE_UPLOAD_ACCEPTED",
"UPLOAD_FILE_ID" : "upload-..."
}
```

To close the modal, I needed to click cancel. Then when I go to the "Owned by Me" tab, the ontology I just tried to create is not listed.

**Comment by ariutta** [comment] 2015-09-04 17:55
Creating a project via the "Upload Project..." button worked in Firefox.

**Comment by hammar** [comment] 2016-01-28 13:06
Is this the intended behavior that you wish "upload & merge" to have, or would you be interested in patches to make this feature capable of uploading and merging other ontologies also? I have a workflow where different parts of an ontology will be produced by different teams and then merged by a QA/RelEng person. That person would benefit from having such a feature, so I'm considering trying to develop it.

**Comment by matthewhorridge** [comment] 2016-01-28 19:16
Yes, it's the intended behaviour.  At least for now.  I think we want something more flexible in the long run, but this will be difficult to implement at the moment due to the way things are serialised.

**Closed** 2019-07-17 20:31 UTC
