### ISSUE TITLE
Bottom-limit of scrolling area in Discussions should not overlap with Ok/Cancel buttons

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/webprotege#318] opened 2015-12-09 23:37 UTC
The per-message buttons for 'Reply' / 'Delete' overlay with the 'Ok' / 'Cancel' buttons when one scrolls all the way down (see screenshot). This may be related to issue #301 - the Discussions scrolling area ends near the bottom of the Ok/Cancel buttons, and it's precisely at the bottom of those buttons that they are "clickable".

![screen shot 2015-12-09 at 15 29 21](https://cloud.githubusercontent.com/assets/4361140/11702331/9b9e87ce-9e8a-11e5-9725-4e203deac06c.png)

**Comment by csnyulas** [comment] 2015-12-09 23:43
Here is another (better) screen shot in FF on Linux
![screenshot from 2015-12-09 15 39 43](https://cloud.githubusercontent.com/assets/2441046/11702444/841ee246-9e8b-11e5-8c5b-1425b56c78f3.png)

**Comment by matthewhorridge** [comment] 2016-02-09 22:46
Duplicate of #251

**Closed by matthewhorridge** 2016-02-09 22:46 UTC
Labels: bug
