### ISSUE TITLE
WebProtege server error while trying to log in

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#243] opened 2015-03-13 22:23 UTC
I am consistently getting the following an error whenever I try to log in to WebProtege:

![screenshot webprotege server error](https://cloud.githubusercontent.com/assets/2441046/6648232/a0f4c6aa-c994-11e4-83b9-5a5103ab358c.png)

It happens from different browsers, from different networks (including Stanford's internal network), and following this error I cannot see my own ontologies listed.

**Comment by matthewhorridge** [comment] 2015-03-13 22:33
Related to the trace below.  Do you have the id of the project by any chance?

```
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at edu.stanford.bmir.protege.web.shared.project.ProjectDetails.<init>(ProjectDetails.java:49)
	at edu.stanford.bmir.protege.web.server.LocalMetaProjectManager.createProjectDetailsFromProjectInstance(LocalMetaProjectManager.java:157)
	at edu.stanford.bmir.protege.web.server.LocalMetaProjectManager.getListableReadableProjects(LocalMetaProjectManager.java:131)
	at edu.stanford.bmir.protege.web.server.dispatch.handlers.GetAvailableProjectsHandler.execute(GetAvailableProjectsHandler.java:39)
	at edu.stanford.bmir.protege.web.server.dispatch.handlers.GetAvailableProjectsHandler.execute(GetAvailableProjectsHandler.java:23)
	at edu.stanford.bmir.protege.web.server.dispatch.impl.DefaultDispatchServiceExecutor.execute(DefaultDispatchServiceExecutor.java:34)
	at edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceImpl.executeAction(DispatchServiceImpl.java:35)```

**Comment by csnyulas** [comment] 2015-03-13 22:51
No. I don't think I have. I think I had 2 or 3 (maybe 4 projects), but I am not sure about the exact name of them either.

**Comment by digosisinfo** [comment] 2016-02-23 14:43
Dear,

I have been tried to login after sign for account, but the system is showing an error like ilustreted in figure below. 

![erro-webprotege](https://cloud.githubusercontent.com/assets/17431368/13254907/46f077ae-da22-11e5-856c-c3a2f28df3d4.png)

I cannot use the system! 

Regards,
Diego

**Comment by tudorache** [comment] 2016-02-23 16:59
@digosisinfo Please check your WebProtege credentials (user name/password). If you cannot remember them, press on the link "Forgot username or password".

If you still have problems logging in, please continue the discussion on the protege-user mailing list:
http://protege.stanford.edu/support.php

This is not a bug, closing.

**Closed by tudorache** 2016-02-23 16:59 UTC
