### ISSUE TITLE
encoder problem

### ISSUE THREAD

**Issue by sshmyeclipse** [protegeproject/webprotege#443] opened 2017-12-28 12:29 UTC
hi,when I used webprotege to edit Chinese words, the Class description for Chinese Words were encoded. For example the Display name is 电池，but the IRI is http://test/ontologies/example/tdb#%E7%94%B5%E6%B1%A0
Can webprotege show the IRI http://test/ontologies/example/tdb#电池？
Thanks!

**Comment by matthewhorridge** [comment] 2018-01-08 14:31
Duplicate of https://github.com/protegeproject/webprotege/issues/442  (fixed for the next version of WebProtege).

**Closed by matthewhorridge** 2018-01-08 14:31 UTC
