### ISSUE TITLE
"post new topic" disabled with "can comment' permission

### ISSUE THREAD

**Issue by zhengj2007** [protegeproject/webprotege#308] opened 2015-10-13 15:40 UTC
I'd like my collaborators to comment the ontology I developed without login in. I set the Project share option as "can comment". However, they cannot add comments using "post new topic" since the button is disabled.

**Comment by csnyulas** [comment] 2015-10-13 18:26
I just tried, and indeed people can't comment on my entities if they are not logged in. This makes sense, because you, as the ontology owner, would want to know who is making the comments. However, once people log in, they can all comment on my ontology that I shared as public for anyone to comment.
I close this issue since this is the intended behavior.

**Closed by csnyulas** 2015-10-13 18:26 UTC

**Comment by tudorache** [comment] 2015-10-13 18:32
@zhengj2007, one idea if your collaborators do not want to create a webprotege account, is to create a group webprotege account, and they can all use the same to comment.

**Comment by zhengj2007** [comment] 2015-10-13 18:40
Thanks for quick reply. 

When I set the project share option "can comment", what users can do without login? What is it different from share option "can view"? Thanks!

**Comment by csnyulas** [comment] 2015-10-13 19:02
If you share your ontology with "Can view" permissions, people will be able to see your ontology, but will not be able to comment, even after they log in. If you set your sharing option to "Can comment", then anybody (or certain people whom you share it with, individually) can view AND comment on your ontology. They cannot comment on your ontology without being logged in, because you need to know who is commenting, and the only way to know that it is if they log in.

**Comment by zhengj2007** [comment] 2015-10-13 19:06
Got it. So, "can comment/edit' only applies to those who login. With this option, I don't need to invite individuals for comment or edit.

**Comment by csnyulas** [comment] 2015-10-13 20:23
Exactly. If you say "Public" and Anyone "Can comment" then anyone with an account on webprotege can comment, once they are logged in. Additionally you can also share your project with certain people who can do more than just comment, such as edit.

**Comment by zhengj2007** [comment] 2015-10-13 20:31
Thanks for explanation.
