### ISSUE TITLE
Unable to upload large ontology file

### ISSUE THREAD

**Issue by hemed** [protegeproject/webprotege#378] opened 2017-02-27 15:28 UTC
I have tried to upload 200MB file to the Webprotege hosted instance and it was unsuccessful.  

However, I managed to upload to a localhost instance running in tomcat but still it is very very slow.
Are there any optimization settings for large files?

**Comment by matthewhorridge** [comment] 2017-02-27 18:28
How much memory have you assigned tomcat?  Would you be able to share the file so that we can see where the issue is?

**Comment by hemed** [comment] 2017-02-28 20:49
Thank you for you reply Matthew. We have tried to assign tomcat up to 12GB of memory but still no luck. I will send the file to you via e-mail.

**Comment by matthewhorridge** [comment] 2017-03-01 01:20
Just a note: The slow down occurs when very large numbers of individuals are displayed.

**Closed** 2017-03-28 21:23 UTC
