### ISSUE TITLE
WebProtegeIRIShortFormProvider throws exception at loading NCI Th.

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#261] opened 2015-04-19 23:05 UTC
This happens with an old (existing) NCI project in WebProtege, or when trying to upload a new version of the NCI Th. in WebProtege.

```
                                                                                               [Sun Apr 19 15:55:45 PDT 2015]
             Ontology loading finished:
             file:/apps/bmir.apps/web-protege-data/data-store/project-data/3ee1bb67-4668-4b6f-9c1f-dadcdc11e67e/ontology-data/root-ontology.binary (Loaded:
             OntologyID(OntologyIRI(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl>)))
[WebProtege] Cached import: OntologyID(OntologyIRI(<http://protege.stanford.edu/plugins/owl/protege>))                                                                               [Sun Apr 19 15:55:45 PDT 2015]
[WebProtege] Project: 3ee1bb67-4668-4b6f-9c1f-dadcdc11e67e                                                                                                                           [Sun Apr 19 15:55:45 PDT 2015]
             Ontology loading completed in 3846 ms.
[WebProtege] ***** SEVERE *****                                                                                                                                                      [Sun Apr 19 15:55:45 PDT 2015]
             An unexpected exception was thrown on the server
             
             Date and time: Sun Apr 19 15:55:45 PDT 2015
             
             User: ttania
             email: ...
             groups:
                ....
             Request URI: /webprotege/webprotege/projectmanager
             Remote address: 67.180.87.67
             Remote host: 67.180.87.67
             
             Headers:
             host: webprotege.stanford.edu
             connection: keep-alive
             content-length: 550
             X-GWT-Permutation: D085FB799EB307EC26EFCE105D8CF627
             Origin: http://webprotege.stanford.edu
             user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36
             content-type: text/x-gwt-rpc; charset=UTF-8
             accept: */*
             referer: http://webprotege.stanford.edu/
             accept-encoding: gzip,deflate
             accept-language: en-US,en;q=0.8
             cookie: JSESSIONID=7D86AD40723A60EC9191D652B517ACB5; COOKIE_DEVICE_CLASS=desktop; __utmt=1; __utma=205289238.212235580.1429481974.1429481974.1429481974.1;
             __utmb=205289238.3.10.1429481974; __utmc=205289238; __utmz=205289238.1429481974.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
             X-GWT-Module-Base: http://webprotege.stanford.edu:8080/webprotege/webprotege/
             
             
             Message: Service method 'public abstract edu.stanford.bmir.protege.web.shared.project.ProjectDetails
             edu.stanford.bmir.protege.web.client.rpc.ProjectManagerService.createNewProject(edu.stanford.bmir.protege.web.client.rpc.data.NewProjectSettings) throws
             edu.stanford.bmir.protege.web.client.rpc.data.NotSignedInException,edu.stanford.bmir.protege.web.shared.project.ProjectAlreadyRegisteredException,edu.stanford.bmir.protege.web.shared.project.ProjectDocumentExistsException'
             threw an unexpected exception: java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
             
             Stack trace:
             
             com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract edu.stanford.bmir.protege.web.shared.project.ProjectDetails
             edu.stanford.bmir.protege.web.client.rpc.ProjectManagerService.createNewProject(edu.stanford.bmir.protege.web.client.rpc.data.NewProjectSettings) throws
             edu.stanford.bmir.protege.web.client.rpc.data.NotSignedInException,edu.stanford.bmir.protege.web.shared.project.ProjectAlreadyRegisteredException,edu.stanford.bmir.protege.web.shared.project.ProjectDocumentExistsException'
             threw an unexpected exception: java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
             at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
             at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
             at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
             at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
             at edu.stanford.bmir.protege.web.server.WebProtegeRemoteServiceServlet.processCall(WebProtegeRemoteServiceServlet.java:151)
             at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
             at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
             at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
             at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
             at edu.stanford.bmir.protege.web.server.filter.WebProtegeWebAppFilter.doFilter(WebProtegeWebAppFilter.java:71)
             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
             at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
             at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
             at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
             at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
             at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
             at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
             at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
             at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:427)
             at org.apache.coyote.ajp.AjpAprProtocol$AjpConnectionHandler.process(AjpAprProtocol.java:384)
             at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1584)
             at java.lang.Thread.run(Thread.java:745)
             Caused by: java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
             at java.net.URLDecoder.decode(URLDecoder.java:187)
             at edu.stanford.bmir.protege.web.server.shortform.WebProtegeIRIShortFormProvider.getShortForm(WebProtegeIRIShortFormProvider.java:109)
             at edu.stanford.bmir.protege.web.server.shortform.WebProtegeShortFormProvider.getShortForm(WebProtegeShortFormProvider.java:26)
             at org.semanticweb.owlapi.util.BidirectionalShortFormProviderAdapter.generateShortForm(BidirectionalShortFormProviderAdapter.java:133)
             at org.semanticweb.owlapi.util.CachingBidirectionalShortFormProvider.add(CachingBidirectionalShortFormProvider.java:114)
             at org.semanticweb.owlapi.util.CachingBidirectionalShortFormProvider.rebuild(CachingBidirectionalShortFormProvider.java:102)
             at org.semanticweb.owlapi.util.BidirectionalShortFormProviderAdapter.<init>(BidirectionalShortFormProviderAdapter.java:102)
             at edu.stanford.bmir.protege.web.server.shortform.WebProtegeBidirectionalShortFormProvider$1.<init>(WebProtegeBidirectionalShortFormProvider.java:39)
             at edu.stanford.bmir.protege.web.server.shortform.WebProtegeBidirectionalShortFormProvider.<init>(WebProtegeBidirectionalShortFormProvider.java:39)
             at edu.stanford.bmir.protege.web.server.owlapi.OWLAPIProject.initialiseProjectMachinery(OWLAPIProject.java:227)
             at edu.stanford.bmir.protege.web.server.owlapi.OWLAPIProject.<init>(OWLAPIProject.java:184)
             at edu.stanford.bmir.protege.web.server.owlapi.OWLAPIProject.getProject(OWLAPIProject.java:134)
             at edu.stanford.bmir.protege.web.server.owlapi.OWLAPIProjectCache.getProjectInternal(OWLAPIProjectCache.java:142)
             at edu.stanford.bmir.protege.web.server.owlapi.OWLAPIProjectCache.getProject(OWLAPIProjectCache.java:110)
             at edu.stanford.bmir.protege.web.server.owlapi.OWLAPIProjectCache.getProject(OWLAPIProjectCache.java:174)
             at edu.stanford.bmir.protege.web.server.owlapi.OWLAPIProjectManager.createNewProject(OWLAPIProjectManager.java:42)
             at edu.stanford.bmir.protege.web.server.ProjectManagerServiceImpl.createNewProject(ProjectManagerServiceImpl.java:97)
             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             at java.lang.reflect.Method.invoke(Method.java:483)
             at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
             ... 23 more

```

**Comment by matthewhorridge** [comment] 2015-04-20 03:30
Duplicate of #238, which has been fixed.

**Closed by matthewhorridge** 2015-04-20 03:30 UTC
